#include <gtest/gtest.h>
#include "operators.h"
#include <fstream>
#include <vector>
#include <cmath>
#include <string>

// ===========================================================================
// NumPy reference alignment tests
// ===========================================================================
// Compares C++ operator output against NumPy-generated reference data.
// Reference files generated by: python tests/gen_phase2_ref.py
// ===========================================================================

static std::vector<float> read_bin(const std::string& path, int count) {
    std::vector<float> data(count);
    std::ifstream f("data/" + path, std::ios::binary);
    EXPECT_TRUE(f.is_open()) << "Cannot open: data/" << path;
    if (!f) return data;
    f.read(reinterpret_cast<char*>(data.data()), count * sizeof(float));
    return data;
}

// ============================================================
// Softmax alignment
// ============================================================

TEST(NumPyAlign, Softmax_Basic) {
    auto in = read_bin("softmax_basic_in.bin", 3);
    auto ref = read_bin("softmax_basic_ref.bin", 3);
    std::vector<float> test(in.begin(), in.end());
    softmax(test.data(), 3);
    for (int i = 0; i < 3; i++)
        EXPECT_NEAR(test[i], ref[i], 1e-5f) << "at index " << i;
}

TEST(NumPyAlign, Softmax_LargeValues) {
    auto in = read_bin("softmax_large_in.bin", 3);
    auto ref = read_bin("softmax_large_ref.bin", 3);
    std::vector<float> test(in.begin(), in.end());
    softmax(test.data(), 3);
    for (int i = 0; i < 3; i++)
        EXPECT_NEAR(test[i], ref[i], 1e-5f) << "at index " << i;
}

TEST(NumPyAlign, Softmax_Negative) {
    auto in = read_bin("softmax_neg_in.bin", 3);
    auto ref = read_bin("softmax_neg_ref.bin", 3);
    std::vector<float> test(in.begin(), in.end());
    softmax(test.data(), 3);
    for (int i = 0; i < 3; i++)
        EXPECT_NEAR(test[i], ref[i], 1e-5f) << "at index " << i;
}

// ============================================================
// LayerNorm alignment
// ============================================================

TEST(NumPyAlign, LayerNorm) {
    auto in = read_bin("layernorm_in.bin", 4);
    auto ref = read_bin("layernorm_ref.bin", 4);
    std::vector<float> out(4);
    float gamma[4] = {1,1,1,1}, beta[4] = {0,0,0,0};
    layernorm(in.data(), 4, 1e-5f, gamma, beta, out.data());
    for (int i = 0; i < 4; i++)
        EXPECT_NEAR(out[i], ref[i], 1e-5f) << "at index " << i;
}

// ============================================================
// GELU alignment
// ============================================================

TEST(NumPyAlign, GELU_Exact) {
    auto in = read_bin("gelu_in.bin", 12);
    auto ref = read_bin("gelu_ref.bin", 12);
    for (int i = 0; i < 12; i++)
        EXPECT_NEAR(gelu_exact(in[i]), ref[i], 1e-5f) << "at x=" << in[i];
}

// ============================================================
// Attention alignment
// ============================================================

TEST(NumPyAlign, Attention) {
    // Read metadata
    int seq_len = 3, d_k = 4, d_v = 4;
    std::ifstream meta("data/attn_meta.txt");
    if (meta.is_open()) {
        std::string line;
        std::getline(meta, line); seq_len = std::stoi(line.substr(line.find('=')+1));
        std::getline(meta, line); d_k = std::stoi(line.substr(line.find('=')+1));
        std::getline(meta, line); d_v = std::stoi(line.substr(line.find('=')+1));
    }

    auto Q = read_bin("attn_Q.bin", seq_len * d_k);
    auto K = read_bin("attn_K.bin", seq_len * d_k);
    auto V = read_bin("attn_V.bin", seq_len * d_v);
    auto ref = read_bin("attn_ref.bin", seq_len * d_v);

    std::vector<float> out;
    scaled_dot_product_attention(Q, K, V, seq_len, d_k, d_v, out);

    EXPECT_EQ(out.size(), ref.size());
    for (size_t i = 0; i < ref.size(); i++)
        EXPECT_NEAR(out[i], ref[i], 1e-4f) << "at index " << i;
}
